<a href="https://colab.research.google.com/github/JMSBornot/PytorchCourseDL/blob/main/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
torch.cuda.is_available()
id = torch.cuda.current_device()
print(f"device id: {id}")
torch.cuda.get_device_name(id)

device id: 0


'Tesla T4'

In [21]:
import numpy as np

# Numpy array
mat = np.random.rand(3,4)
print(mat)
print(type(mat))
print(mat.dtype)

# Pytorch tensor array
mat2 = torch.randn(3,4)
print(mat2)
print(type(mat2))
print(mat2.dtype)

# Create a tensor from the Numpy array
mat_tensor = torch.tensor(mat)
print(mat_tensor)
print(type(mat_tensor))
print(mat_tensor.dtype)

[[0.86957673 0.32973682 0.66995925 0.10087561]
 [0.78584467 0.6850799  0.78667126 0.36704781]
 [0.86503571 0.17643936 0.89668342 0.53265743]]
<class 'numpy.ndarray'>
float64
tensor([[ 8.9895e-01,  2.0840e+00, -8.6006e-01, -5.1121e-01],
        [-3.0922e-01,  4.2023e-01, -3.4599e-01, -1.0902e-03],
        [-1.2063e+00, -1.5927e-01, -1.2753e-01,  1.5453e+00]])
<class 'torch.Tensor'>
torch.float32
tensor([[0.8696, 0.3297, 0.6700, 0.1009],
        [0.7858, 0.6851, 0.7867, 0.3670],
        [0.8650, 0.1764, 0.8967, 0.5327]], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64


In [9]:
mylist = [[1,2,3,4], [5,6,7,8]]
print(mylist)
type(mylist)

[[1, 2, 3, 4], [5, 6, 7, 8]]


list

In [22]:
tensor_3d = torch.zeros(2,3,4,dtype=torch.float64) # by default precision is 32 bits
tensor_3d[1,2,2] = 1
print(tensor_3d)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.]]], dtype=torch.float64)


In [29]:
seq = torch.arange(10)
print(seq)
# reshape and view are similar
print(seq.reshape(2,5))
print(seq.view(2,5))

# Reshape if you don't know the size of a dimension using -1
mat = seq.reshape(2,-1)
print(mat)
print(mat.size())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.Size([2, 5])


# **Critical note**
Both, reshape and view, create references

In [40]:
seq = torch.arange(10)
mat = seq.reshape(-1,2)
mat2 = mat.clone() # clone to copy the values, i.e., break the reference
seq[7] = 42
print(seq)
print(mat)
print(mat2)
print(mat[3,])
print(mat[3,:]) # also allow Matlab notation

print(mat[:,1])  # by default slicing breaks the shape (forced to use colon for the dimensions at the left)
print(mat[:,1:]) # it must include colon to preserve the shape

tensor([ 0,  1,  2,  3,  4,  5,  6, 42,  8,  9])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6, 42],
        [ 8,  9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([ 6, 42])
tensor([ 6, 42])
tensor([ 1,  3,  5, 42,  9])
tensor([[ 1],
        [ 3],
        [ 5],
        [42],
        [ 9]])
